"use strict";

const crypto=require("node:crypto"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {execFileSync}=require("node:child_process");
const {scanPackageTree}=require("./package-hygiene");
const {assertAcceptedPatchReport}=require("./package-deb");
const {RPM_POST_INSTALL,RPM_PRE_UNINSTALL}=require("./package-contract");
const {readBuilderProvenance,validateBuildInfo}=require("./release-metadata");
const {validateAppJavaScript}=require("./validate-app-javascript");
const {readPngDimensions}=require("./icon");

const DEB_CONTROL_MEMBERS=new Set(["control","postinst","prerm","postrm"]);
const NATIVE_PAYLOAD_FILES=new Set([
  "usr/bin/factory-update-manager",
  "usr/lib/factory-desktop/factory-droid-daemon",
  "usr/lib/factory-desktop/update-bridge.cjs",
  "usr/lib/systemd/user/factory-droid-daemon.service",
  "usr/lib/systemd/user/factory-update-manager.service",
  "usr/share/applications/factory-desktop.desktop",
  "usr/share/icons/hicolor/512x512/apps/factory-desktop.png",
  "usr/share/icons/hicolor/scalable/apps/factory-desktop.svg",
  "usr/share/polkit-1/actions/org.factory.desktop.update-manager.policy",
]);

function normalizeText(value){return String(value).replace(/\r\n/g,"\n").replace(/\n+$/,"");}
function sha256File(file){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}
function assertNativePackageMetadata(format,metadata,expected){const architecture=format==="deb"?"amd64":"x86_64",expectedVersion=typeof expected==="string"?expected:expected.packageVersion,expectedRelease=typeof expected==="string"?null:expected.packageRelease;if(metadata.name!=="factory-desktop")throw new Error(`${format}: unexpected package name: ${metadata.name}`);if(metadata.version!==expectedVersion)throw new Error(`${format}: package version ${metadata.version} does not match expected package version ${expectedVersion}`);if(format==="rpm"&&expectedRelease!==null&&metadata.release!==expectedRelease)throw new Error(`${format}: package release ${metadata.release} does not match expected package release ${expectedRelease}`);if(metadata.architecture!==architecture)throw new Error(`${format}: unexpected package architecture: ${metadata.architecture}`);}
function assertAllowedNativePayload(root,format){const walk=directory=>{for(const entry of fs.readdirSync(directory,{withFileTypes:true})){const full=path.join(directory,entry.name),relative=path.relative(root,full).split(path.sep).join("/");if(entry.isDirectory()){walk(full);continue}const allowed=relative.startsWith("opt/Factory/")||relative.startsWith("usr/lib/factory-desktop/update-builder/")||(format==="rpm"&&relative.startsWith("usr/lib/.build-id/"))||NATIVE_PAYLOAD_FILES.has(relative);if(!allowed)throw new Error(`${format}: unexpected package payload path: ${relative}`)}};walk(root);}
function assertExactDebMaintainerScripts(controlRoot){for(const entry of fs.readdirSync(controlRoot,{withFileTypes:true})){if(!entry.isFile()||!DEB_CONTROL_MEMBERS.has(entry.name))throw new Error(`unexpected deb control member: ${entry.name}`)}for(const name of ["postinst","prerm","postrm"]){const actual=path.join(controlRoot,name),expected=path.resolve(__dirname,"..","packaging","linux",`factory-desktop.${name}`);if(!fs.statSync(actual,{throwIfNoEntry:false})?.isFile()||!fs.readFileSync(actual).equals(fs.readFileSync(expected)))throw new Error(`deb maintainer script does not match repository contract: ${name}`)}}
function assertRpmScriptlets(scriptlets){if(scriptlets.postinProgram!=="/bin/sh"||normalizeText(scriptlets.postin)!==normalizeText(RPM_POST_INSTALL))throw new Error("unexpected RPM scriptlet: postin");if(scriptlets.preunProgram!=="/bin/sh"||normalizeText(scriptlets.preun)!==normalizeText(RPM_PRE_UNINSTALL))throw new Error("unexpected RPM scriptlet: preun");for(const name of ["prein","postun"]){if(scriptlets[`${name}Program`]!=="(none)"||scriptlets[name]!=="(none)")throw new Error(`unexpected RPM scriptlet: ${name}`)}}
function packageBuildInfo(root,format){const appRoot=format==="appimage"?path.join(root,"usr","lib","factory-desktop"):path.join(root,"opt","Factory");const info=JSON.parse(fs.readFileSync(path.join(appRoot,"build-info.json"),"utf8"));validateBuildInfo(info,{expectedFormat:format});return info;}
function expectedFactoryVersion(root,format){return packageBuildInfo(root,format).factoryVersion;}
function field(command,args){return execFileSync(command,args,{encoding:"utf8",stdio:["ignore","pipe","pipe"]}).trim();}

function assertNativeUpdaterBridge(root,format){const bridge=path.join(root,"usr","lib","factory-desktop","update-bridge.cjs"),builderBridge=path.join(root,"usr","lib","factory-desktop","update-builder","packaging","linux","update-bridge.cjs"),policy=path.join(root,"usr","share","polkit-1","actions","org.factory.desktop.update-manager.policy"),found=findNamed(root,"update-bridge.cjs");if(format==="appimage"){if(found.length)throw new Error("AppImage must not contain update-bridge.cjs");return}if(!found.includes(bridge)||found.some(file=>file!==bridge&&file!==builderBridge))throw new Error(`${format}: update bridge must use the fixed package path`);const metadata=fs.lstatSync(bridge,{throwIfNoEntry:false});if(!metadata?.isFile()||metadata.isSymbolicLink())throw new Error(`${format}: update bridge must be a regular package-owned file`);if((metadata.mode&0o777)!==0o644)throw new Error(`${format}: update bridge must have mode 0644`);const source=fs.readFileSync(bridge,"utf8");if(!source.includes('const HELPER = "/usr/bin/factory-update-manager"')||source.includes("FACTORY_UPDATE_MANAGER_PATH"))throw new Error(`${format}: update bridge helper path is not fixed`);const policyText=fs.readFileSync(policy,"utf8"),action=policyText.match(/<action id="org\.factory\.desktop\.update-manager\.install-approved-package">([\s\S]*?)<\/action>/)?.[1];if(!action||!/<allow_active>no<\/allow_active>/.test(action)||!/<annotate key="org\.freedesktop\.policykit\.exec\.argv1">install-approved-package<\/annotate>/.test(action))throw new Error(`${format}: approved install policy must remain inactive`);}

function assertNativeBuilderProvenance(root,format,expectedCommit){const builderRoot=path.join(root,"usr","lib","factory-desktop","update-builder"),provenance=path.join(builderRoot,"build-provenance.json"),metadata=fs.lstatSync(provenance,{throwIfNoEntry:false});if(format==="appimage"){if(metadata)throw new Error("AppImage must not contain native update-builder provenance");return}if(!metadata?.isFile()||metadata.isSymbolicLink()||(metadata.mode&0o777)!==0o644)throw new Error(`${format}: update-builder provenance must be a mode 0644 non-writable regular file`);const actual=readBuilderProvenance(builderRoot);if(actual!==expectedCommit)throw new Error(`${format}: update-builder provenance commit mismatch`);}

function assertBridgeArchiveOwnership(artifact,format){const target="usr/lib/factory-desktop/update-bridge.cjs";if(format==="deb"){const line=field("dpkg-deb",["--contents",artifact]).split("\n").find(value=>value.trimEnd().endsWith(`./${target}`));if(!line||!/^\-rw-r--r--\s+root\/root\s/.test(line))throw new Error("deb: update bridge must be root-owned mode 0644 in the archive");return}const line=field("rpm",["-qp","--qf","[%{FILENAMES}|%{FILEUSERNAME}|%{FILEGROUPNAME}|%{FILEMODES:perms}\\n]",artifact]).split("\n").find(value=>value.split("|")[0]===`/${target}`);if(!line||!line.endsWith("|root|root|-rw-r--r--"))throw new Error("rpm: update bridge must be root-owned mode 0644 in the archive");}

function assertBuilderProvenanceArchiveOwnership(artifact,format){const target="usr/lib/factory-desktop/update-builder/build-provenance.json";if(format==="deb"){const line=field("dpkg-deb",["--contents",artifact]).split("\n").find(value=>value.trimEnd().endsWith(`./${target}`));if(!line||!/^\-rw-r--r--\s+root\/root\s/.test(line))throw new Error("deb: update-builder provenance must be root-owned mode 0644 in the archive");return}const line=field("rpm",["-qp","--qf","[%{FILENAMES}|%{FILEUSERNAME}|%{FILEGROUPNAME}|%{FILEMODES:perms}\\n]",artifact]).split("\n").find(value=>value.split("|")[0]===`/${target}`);if(!line||!line.endsWith("|root|root|-rw-r--r--"))throw new Error("rpm: update-builder provenance must be root-owned mode 0644 in the archive");}

function findNamed(root,name){const found=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.name===name)found.push(f);if(e.isDirectory())walk(f)}};walk(root);return found}
function installedDesktop(root,format){const preferred=format==="appimage"?path.join(root,"factory-desktop.desktop"):path.join(root,"usr","share","applications","factory-desktop.desktop");if(fs.existsSync(preferred))return preferred;return findNamed(root,"factory-desktop.desktop").find((file)=>!file.includes(`${path.sep}update-builder${path.sep}`));}
function assertPackageIcon(root,format){const relative=format==="appimage"?"factory-desktop.png":"usr/share/icons/hicolor/512x512/apps/factory-desktop.png",icon=path.join(root,...relative.split("/")),metadata=fs.lstatSync(icon,{throwIfNoEntry:false});if(!metadata?.isFile()||metadata.isSymbolicLink())throw new Error(`${format}: package icon must be a regular file: ${relative}`);if((metadata.mode&0o777)!==0o644)throw new Error(`${format}: package icon must have mode 0644: ${relative}`);let dimensions;try{dimensions=readPngDimensions(fs.readFileSync(icon));}catch(error){throw new Error(`${format}: package icon is not a valid PNG: ${error.message}`);}if(dimensions.width!==512||dimensions.height!==512)throw new Error(`${format}: package icon must be exactly 512x512: ${relative}`);return{path:relative,width:dimensions.width,height:dimensions.height,mode:metadata.mode&0o777};}
function assertDesktopIdentity(root,format,text){for(const line of ["StartupWMClass=factory","X-GNOME-WMClass=factory"]){if(!text.split("\n").includes(line))throw new Error(`${format}: desktop entry missing ${line}`);}if(format!=="appimage"){for(const hint of ["BAMF_DESKTOP_FILE_HINT=/usr/share/applications/factory-desktop.desktop","CHROME_DESKTOP=factory-desktop.desktop"]){if(!text.includes(hint))throw new Error(`${format}: desktop entry missing ${hint}`);}}else{const appRun=findNamed(root,"AppRun")[0],appRunText=appRun?fs.readFileSync(appRun,"utf8"):"";if(!appRun||!appRunText.includes('export CHROME_DESKTOP="factory-desktop.desktop"')||!appRunText.includes('export BAMF_DESKTOP_FILE_HINT="$APPDIR/factory-desktop.desktop"'))throw new Error("appimage: AppRun desktop identity hints are missing");}return{startupWMClass:"factory",gnomeWMClass:"factory",desktopHints:true};}
function inspectExtracted(root,format){const hygiene=scanPackageTree(root,{workspaceRoot:process.cwd()});const appRoot=format==="appimage"?path.join(root,"usr","lib","factory-desktop"):path.join(root,"opt","Factory"),javascriptSyntax=validateAppJavaScript(appRoot);const desktop=installedDesktop(root,format);if(!desktop)throw new Error(`${format}: factory-desktop.desktop missing`);const text=fs.readFileSync(desktop,"utf8");if(!text.includes("MimeType=x-scheme-handler/factory-desktop;"))throw new Error(`${format}: factory-desktop MimeType missing`);const desktopIdentity=assertDesktopIdentity(root,format,text),icon=assertPackageIcon(root,format);assertNativeUpdaterBridge(root,format);
  const buildInfo=packageBuildInfo(root,format);assertNativeBuilderProvenance(root,format,buildInfo.repositoryCommit);const patchReport=assertAcceptedPatchReport(appRoot);const patchReportSha256=sha256File(path.join(appRoot,".factory-linux","patch-report.json"));if(buildInfo.patchReportSha256!==patchReportSha256)throw new Error(`${format}: build-info patch report hash mismatch`);const asarSha256=sha256File(path.join(appRoot,"resources","app.asar"));if(buildInfo.patchedAsarSha256!==asarSha256)throw new Error(`${format}: build-info patched ASAR hash mismatch`);
  const services=findNamed(root,"factory-droid-daemon.service").filter((file)=>format==="appimage"||file.includes(`${path.sep}usr${path.sep}lib${path.sep}systemd${path.sep}user${path.sep}`)),updateServices=findNamed(root,"factory-update-manager.service").filter((file)=>format==="appimage"||file.includes(`${path.sep}usr${path.sep}lib${path.sep}systemd${path.sep}user${path.sep}`)),policies=findNamed(root,"org.factory.desktop.update-manager.policy").filter((file)=>format==="appimage"||file.includes(`${path.sep}usr${path.sep}share${path.sep}polkit-1${path.sep}actions${path.sep}`)),updaters=findNamed(root,"factory-update-manager").filter((file)=>format==="appimage"||file.includes(`${path.sep}usr${path.sep}bin${path.sep}`));
  const bundledDroid=findNamed(root,"droid").filter((file)=>file.includes(`${path.sep}resources${path.sep}bin${path.sep}`));if(bundledDroid.length)throw new Error(`${format}: proprietary resources/bin/droid is present`);
  let keyringEnv=false;
  if(format==="appimage"){if(services.length||policies.length||updaters.length)throw new Error("AppImage contains native updater integration");const appRun=findNamed(root,"AppRun")[0];const appRunText=appRun?fs.readFileSync(appRun,"utf8"):"";if(!appRun||!appRunText.includes("FACTORY_UPDATE_MANAGER_UNAVAILABLE"))throw new Error("AppImage AppRun lacks unavailable updater state");keyringEnv=appRunText.includes("FACTORY_DISABLE_KEYRING=1");}
  else {if(!services.length)throw new Error(`${format}: droid daemon service missing`);if(!updateServices.length)throw new Error(`${format}: update-manager service missing`);if(!policies.length)throw new Error(`${format}: polkit policy missing`);if(!updaters.length)throw new Error(`${format}: update-manager binary missing`);keyringEnv=text.includes("FACTORY_DISABLE_KEYRING=1");}
  if(!keyringEnv)throw new Error(`${format}: FACTORY_DISABLE_KEYRING=1 missing`);
  return{format,patchReport,patchReportSha256,buildInfo,hygiene,javascriptSyntax,desktop,icon,desktopIdentity,services:services.length,updateServices:updateServices.length,policies:policies.length,updaters:updaters.length,bundledDroid:bundledDroid.length,keyringEnv,startupWMClass:true,protocolMime:true};}

function inspectPackage(artifact){artifact=path.resolve(artifact);const tempRoot=fs.mkdtempSync(path.join(os.tmpdir(),"factory-inspect-"));let root=path.join(tempRoot,"payload"),format,metadata,controlRoot,scriptlets;
  try{
    if(artifact.endsWith(".deb")){format="deb";metadata={name:field("dpkg-deb",["-f",artifact,"Package"]),version:field("dpkg-deb",["-f",artifact,"Version"]),architecture:field("dpkg-deb",["-f",artifact,"Architecture"])};controlRoot=path.join(tempRoot,"control");execFileSync("dpkg-deb",["--control",artifact,controlRoot],{stdio:"ignore"});assertExactDebMaintainerScripts(controlRoot);execFileSync("dpkg-deb",["--contents",artifact],{stdio:"pipe"});execFileSync("dpkg-deb",["--extract",artifact,root],{stdio:"ignore"});}
    else if(artifact.endsWith(".rpm")){format="rpm";const query=tag=>field("rpm",["-qp","--qf",`%{${tag}}`,artifact]);metadata={name:query("NAME"),version:query("VERSION"),release:query("RELEASE"),architecture:query("ARCH")};scriptlets={postinProgram:query("POSTINPROG"),postin:query("POSTIN"),preinProgram:query("PREINPROG"),prein:query("PREIN"),preunProgram:query("PREUNPROG"),preun:query("PREUN"),postunProgram:query("POSTUNPROG"),postun:query("POSTUN")};assertRpmScriptlets(scriptlets);execFileSync("rpm",["-qlp",artifact],{stdio:"pipe"});fs.mkdirSync(root,{recursive:true});const cpioPath=path.join(root,"payload.cpio"),fd=fs.openSync(cpioPath,"w");try{execFileSync("rpm2cpio",[artifact],{cwd:root,stdio:["ignore",fd,"ignore"]})}finally{fs.closeSync(fd)}execFileSync("cpio",["-idmu","--quiet","--file",cpioPath],{cwd:root,stdio:"ignore"});fs.rmSync(cpioPath);}
    else if(artifact.endsWith(".AppImage")){format="appimage";fs.mkdirSync(root,{recursive:true});execFileSync(artifact,["--appimage-extract"],{cwd:root,env:{...process.env,APPIMAGE_EXTRACT_AND_RUN:"1"},stdio:"ignore"});root=path.join(root,"squashfs-root");}
    else throw new Error(`Unknown package format: ${artifact}`);
    const embeddedBuildInfo=packageBuildInfo(root,format);if(format!=="appimage"){assertNativePackageMetadata(format,metadata,embeddedBuildInfo);assertAllowedNativePayload(root,format);assertBridgeArchiveOwnership(artifact,format);assertBuilderProvenanceArchiveOwnership(artifact,format);}
    const inspection=inspectExtracted(root,format);return{...inspection,packageName:metadata?.name??"factory-desktop",version:inspection.buildInfo.factoryVersion,packageVersion:metadata?.version??inspection.buildInfo.packageVersion,packageRelease:metadata?.release??inspection.buildInfo.packageRelease,packageSha256:sha256File(artifact)};
  }finally{fs.rmSync(tempRoot,{recursive:true,force:true});}}

if(require.main===module){try{console.log(JSON.stringify(inspectPackage(process.argv[2]),null,2))}catch(e){console.error(`Package inspection failed: ${e.message}`);process.exit(1)}}
module.exports={assertAllowedNativePayload,assertBuilderProvenanceArchiveOwnership,assertDesktopIdentity,assertExactDebMaintainerScripts,assertNativeBuilderProvenance,assertNativePackageMetadata,assertNativeUpdaterBridge,assertPackageIcon,assertRpmScriptlets,inspectExtracted,inspectPackage,sha256File};
